#!/usr/bin/env node
/**
 * seller.mjs — a selling agent for the dfmi chain, built on the Claude Agent SDK.
 *
 * It uses two tool sets:
 *   dfmi-paykit (external MCP server, stdio)  — create_invoice, check_payment, send_reminder, list_invoices
 *   seller-goods (in-process MCP server)      — deliver_goods(invoice_id): releases the goods ONLY if the
 *                                               invoice is settled on-chain. The check is in the tool's code,
 *                                               not in the prompt, so the model cannot be talked into delivering early.
 *
 * Usage:
 *   node seller.mjs "Sell the September market report to 0x5050… for 0.02 dUSD, due in 7 days."
 *   node seller.mjs "Has inv_2a45e5acb8e5 been paid? If so, deliver it. If not, draft a polite reminder."
 *   node seller.mjs --repl            # interactive
 *
 * Requires: ANTHROPIC_API_KEY (or a logged-in Claude Code), Node 18+, paykit installed next to this folder.
 */
import { query, createSdkMcpServer, tool } from '@anthropic-ai/claude-agent-sdk';
import { z } from 'zod';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createInterface } from 'node:readline';
import { loadConfig } from '../paykit/src/config.mjs';
import { PayKit } from '../paykit/src/paykit.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const PAYKIT_SERVER = resolve(HERE, '..', 'paykit', 'src', 'server.mjs');
const PAYKIT_CONFIG = resolve(HERE, '..', 'paykit', 'paykit.config.json');

// The seller's own copy of paykit, used by the delivery gate. Same invoice store as the MCP server.
const cfg = loadConfig(PAYKIT_CONFIG);
const kit = new PayKit(cfg);

// ---------------------------------------------------------------- the goods (demo catalog)
const CATALOG = {
  'market-report': () => `dfmi market report — ${new Date().toISOString().slice(0, 10)}\n` +
    `Services listed: 5 · Settled this week: see facilitator catalog · Chain: ${cfg.chain} · Unit: ${cfg.symbol}\n` +
    `(demo deliverable generated by the seller agent after on-chain settlement)`,
};

// ---------------------------------------------------------------- delivery gate: enforced in code
const goods = createSdkMcpServer({
  name: 'seller-goods',
  version: '0.1.0',
  instructions: 'deliver_goods releases the product for an invoice. It verifies settlement on-chain itself and refuses if the invoice is not paid. Do not try to deliver any other way.',
  tools: [
    tool('deliver_goods', 'Release the goods for a settled invoice. Verifies on-chain settlement before releasing; refuses otherwise.',
      { invoice_id: z.string(), product: z.enum(Object.keys(CATALOG)).default('market-report') },
      async ({ invoice_id, product }) => {
        // The gate: re-check the chain right now. The model's belief about payment is irrelevant.
        const st = await kit.checkPayment({ invoice_id });
        if (st.status !== 'paid') {
          return { isError: true, content: [{ type: 'text', text: `Refused: invoice ${invoice_id} is "${st.status}", not "paid". Nothing delivered.` }] };
        }
        const body = CATALOG[product]();
        return { content: [{ type: 'text', text: JSON.stringify({ delivered: true, invoice_id, tx_hash: st.settlement.tx_hash, payer: st.settlement.payer_address, goods: body }, null, 2) }] };
      }),
  ],
});

// ---------------------------------------------------------------- the agent
const SYSTEM = `You are a selling agent on the dfmi network (chain ${cfg.chain}, unit ${cfg.symbol}).
You sell one product: "market-report". Your payee address is ${process.env.SELLER_ADDRESS ?? '0x5050A4F4b3f9338C3472dcC01A87C76A144b3c9c'}.

Rules:
- To sell, create an invoice with create_invoice and give the buyer the exact_amount, pay_to and chain. Never quote a rounded amount; the exact suffix is how payment is matched.
- Before delivering anything, call check_payment. Only call deliver_goods when check_payment says "paid". deliver_goods verifies the chain itself and will refuse otherwise; do not argue with it.
- If check_payment says "unknown", say the chain could not be read and do not deliver. "unknown" is not "unpaid".
- If an invoice is open or overdue and the user asks you to follow up, use send_reminder to draft text and show the draft. You do not send messages yourself.
- Be brief. Report invoice ids, exact amounts and transaction hashes verbatim.`;

async function run(prompt) {
  const q = query({
    prompt,
    options: {
      systemPrompt: SYSTEM,
      mcpServers: {
        'dfmi-paykit': { type: 'stdio', command: 'node', args: [PAYKIT_SERVER, PAYKIT_CONFIG] },
        'seller-goods': goods,
      },
      allowedTools: [
        'mcp__dfmi-paykit__create_invoice', 'mcp__dfmi-paykit__check_payment',
        'mcp__dfmi-paykit__send_reminder', 'mcp__dfmi-paykit__list_invoices',
        'mcp__seller-goods__deliver_goods',
      ],
      disallowedTools: ['Bash', 'Write', 'Edit', 'Read', 'WebFetch', 'WebSearch'],
      permissionMode: 'dontAsk',
      maxTurns: 12,
    },
  });

  for await (const m of q) {
    if (m.type === 'assistant') {
      for (const b of m.message.content ?? []) {
        if (b.type === 'text' && b.text.trim()) console.log(b.text.trim());
        if (b.type === 'tool_use') console.error(`  ↳ ${b.name}(${JSON.stringify(b.input)})`);
      }
    } else if (m.type === 'result') {
      console.error(`— done (${m.subtype}${m.total_cost_usd != null ? `, $${m.total_cost_usd.toFixed(4)}` : ''})`);
    }
  }
}

const argv = process.argv.slice(2);
if (argv[0] === '--repl') {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = () => rl.question('seller> ', async (line) => { if (!line.trim()) return ask(); await run(line); ask(); });
  ask();
} else if (argv.length) {
  await run(argv.join(' '));
} else {
  console.error('usage: node seller.mjs "<instruction>"   |   node seller.mjs --repl');
  process.exit(2);
}
